### ISSUE TITLE
Turn interpreter into a module, and create another script for actually executing the code.

### ISSUE THREAD

**Issue by systocrat** [intangere/Intersect#1]
This would be better for two reasons:
1. integration into other code would be easier for developers, as there would be separation between the interpreter code and the code that runs/builds intersect code
2. This makes it easier to write your own build tools later on, when you expose the libraries for parsing and building ASTs.

Cheers,
Dan

**Comment by intangere** [comment]
Separated the main intersect file and interpreter.
